#!/usr/bin/env python
import os

libname = "hashrace_runtime"
projectdir = "../../../Godot"

local_env = Environment(tools=["default"], PLATFORM="")
env = local_env.Clone()
env = SConscript("godot-cpp/SConstruct", {"api_version": "4.7", "env": env})

env.Append(CPPPATH=["src", ".."])
env.Append(CXXFLAGS=["-Wall", "-Wextra"] if env.get("platform") != "windows" else [])

sources = Glob("src/*.cpp")
sources += ["../hashrace_catalog.cpp", "../hashrace_simulation.cpp"]

suffix = env["suffix"].replace(".dev", "").replace(".universal", "")
lib_filename = "{}{}{}{}".format(
    env.subst("$SHLIBPREFIX"), libname, suffix, env.subst("$SHLIBSUFFIX")
)

library = env.SharedLibrary(
    "bin/{}/{}".format(env["platform"], lib_filename),
    source=sources,
)

copy = env.Install("{}/bin/{}/".format(projectdir, env["platform"]), library)
Default(library, copy)
