extends SceneTree

const SCRIPTS: Array[String] = [
    "res://data/item_resource.gd",
    "res://data/item_library.gd",
    "res://components/building/placement_feedback.gd",
    "res://components/building/rack_slot.gd",
    "res://components/building/rack_container.gd",
    "res://components/state_machine/machine_state_controller.gd",
    "res://systems/infrastructure_visual_catalog.gd",
    "res://systems/energy_visual_catalog.gd",
    "res://systems/physical_placement_grid.gd",
    "res://systems/simulation_manager.gd",
    "res://scripts/mining_ops_widget.gd",
    "res://scripts/negotiation_scene.gd",
    "res://systems/negotiation_manager.gd",
    "res://scripts/world_v068.gd",
    "res://scripts/world_v070.gd",
    "res://scripts/world_v072.gd",
    "res://scripts/world_v073.gd",
    "res://scripts/world_v080.gd",
    "res://scripts/world_v082.gd",
    "res://scripts/world_v085.gd",
    "res://scripts/world_v086.gd",
    "res://scripts/character_sprite_rig.gd",
    "res://scripts/character_preview.gd",
    "res://scripts/default_player_sprite_sheet.gd",
    "res://scripts/npc_miner_sprite_sheet.gd",
    "res://scripts/default_player_visual.gd",
    "res://scripts/visual_target_hud.gd",
    "res://scripts/priority_asset_catalog.gd",
    "res://scripts/dirt_road_catalog.gd",
    "res://scripts/grass_terrain_catalog.gd",
    "res://scripts/industrial_road_catalog.gd",
    "res://scripts/utility_props_catalog.gd",
    "res://scripts/wind_turbine_catalog.gd",
    "res://scripts/asic_air_s19j_catalog.gd",
    "res://scripts/electrical_distribution_catalog.gd",
    "res://scripts/world_v087.gd",
    "res://scripts/world_scale_rules.gd",
    "res://scripts/camera_proportion_controller.gd",
    "res://autoloads/scene_manager.gd",
    "res://components/world/doorway.gd",
    "res://components/world/roof_fade_area.gd",
    "res://scripts/world_v088.gd",
    "res://scripts/world_v089.gd",
    "res://scripts/world_v090.gd",
    "res://scripts/world_v091.gd",
    "res://scripts/world_v092.gd",
    "res://scripts/world_v093.gd",
    "res://scripts/world_v111.gd",
    "res://scripts/world_v114.gd",
    "res://scripts/world_v115.gd",
    "res://scripts/world_v116.gd",
    "res://scripts/world_v117.gd",
    "res://scripts/world_v118.gd",
    "res://scripts/world_v119.gd",
    "res://scripts/world_v120.gd",
    "res://scripts/world_v121.gd",
    "res://scripts/world_v122.gd",
    "res://scripts/world_v123.gd",
    "res://scripts/world_v124.gd",
    "res://scripts/world_v125.gd",
    "res://scripts/world_v126.gd",
    "res://scripts/world_v127.gd",
    "res://scripts/world_v128.gd",
    "res://scripts/world_v129.gd",
    "res://scripts/world_v138.gd",
    "res://scripts/world_v139.gd",
    "res://scripts/world_v140.gd",
    "res://scripts/world_v141.gd",
    "res://scripts/world_v142.gd",
    "res://scripts/world_v143.gd",
    "res://scripts/world_v144.gd",
    "res://scripts/world_v145.gd",
]

func _initialize() -> void:
    for path in SCRIPTS:
        print("MODULAR PARSE: ", path)
        var script: Script = load(path) as Script
        if script == null or not script.can_instantiate():
            push_error("MODULAR PARSE FAIL: " + path)
            quit(1)
            return
    print("MODULAR PARSE PASS")
    quit(0)
